baselines:
  - id: persistence
    type: deterministic
  - id: linear_trend
    type: deterministic
  - id: random_walk_drift
    type: stochastic
  - id: ets_local_level
    type: probabilistic
    calibration: NGR
  - id: equal_weight_combination
    type: ensemble
  - id: deep_learning_baseline
    type: probabilistic
    include_if_nested_cv_win: true
  - id: llm_guess
    type: scenario_only
