- id: real_gdp_growth
  source: "BEA NIPA; ALFRED"
  unit: percent_yoy
  transform: z
  data_vintage_available: true
  scenario_only: false

- id: cpi_inflation
  source: "BLS CPI-U; ALFRED"
  unit: percent_yoy
  transform: z
  data_vintage_available: true
  scenario_only: false

- id: unemployment_rate
  source: "BLS; ALFRED"
  unit: percent
  transform: z
  data_vintage_available: true
  scenario_only: false

- id: labor_force_participation
  source: "BLS; ALFRED"
  unit: percent
  transform: z
  data_vintage_available: true
  scenario_only: false

- id: treasury_10y_yield
  source: "FRED DGS10; ALFRED"
  unit: percent
  transform: z
  data_vintage_available: true
  scenario_only: false

- id: term_spread_10y_3m
  source: "FRED DGS10 minus TB3MS; ALFRED"
  unit: percentage_points
  transform: z
  data_vintage_available: true
  scenario_only: false

- id: housing_starts_total
  source: "Census; ALFRED"
  unit: thousands_sa
  transform: z
  data_vintage_available: true
  scenario_only: false

- id: industrial_production
  source: "Fed G.17; ALFRED"
  unit: index
  transform: z
  data_vintage_available: true
  scenario_only: false

- id: federal_spending_gdp_share
  source: "OMB Historical Tables; ALFRED where possible"
  unit: percent_gdp
  transform: z
  data_vintage_available: true
  scenario_only: false

- id: consumer_sentiment
  source: "Univ. Michigan ICS"
  unit: index
  transform: z
  data_vintage_available: false
  scenario_only: true

- id: sp500_real_total_return
  source: "S&P; Shiller"
  unit: percent_yoy
  transform: z
  data_vintage_available: false
  scenario_only: true

- id: baa_aaa_spread
  source: "FRED/ICE"
  unit: percentage_points
  transform: z
  data_vintage_available: false
  scenario_only: true

- id: immigration_rate
  source: "DHS Yearbook"
  unit: per_thousand_pop
  transform: z
  data_vintage_available: false
  scenario_only: true

- id: union_membership_rate
  source: "BLS CPS"
  unit: percent
  transform: z
  data_vintage_available: false
  scenario_only: true

- id: gini_income_inequality
  source: "Census CPS ASEC"
  unit: index
  transform: z
  data_vintage_available: false
  scenario_only: true

