transforms:
  zscore:
    method: zscore
    train_window: 'up_to_origin'
  logit_clip:
    method: logit
    clip: [0.01, 0.99]
  boxcox:
    method: boxcox
    lambda_search: true
imputation:
  method: forward_fill_then_mean
  flag_column: '_imputed'
outliers:
  method: iqr
  k: 3.0
break_detection:
  methods: [PELT, BaiPerron]
  pelt_penalty: bic
  choose_by_nested_cv: true
