indicators:
  - id: real_gdp_growth
    source: BEA
    unit: pct_yoy
    transform: zscore
    data_vintage_available: true
    revision_policy: 'standard'
    mode_changes: []
    break_flags: []
    diversity_category: 'macro'
    snapshot_frequency: 'annual'
    archival_format: 'csv'
    hash_method: 'sha256'
    fixed_preprocessing_version: 'v1'
    pre1945_ok: false
    pre1985_ok: true
  - id: unemployment_rate
    source: BLS
    unit: pct
    transform: zscore
    data_vintage_available: true
    revision_policy: 'revisions_expected'
    break_flags: []
    diversity_category: 'labor'
    snapshot_frequency: 'monthly_to_annual'
    archival_format: 'csv'
    hash_method: 'sha256'
    fixed_preprocessing_version: 'v1'
    pre1945_ok: false
    pre1985_ok: true
  - id: public_trust_government
    source: Gallup
    unit: pct
    transform: logit_clip
    data_vintage_available: true
    diversity_category: 'survey'
    fixed_preprocessing_version: 'v1'
    pre1945_ok: false
    pre1985_ok: false
  - id: house_polarization_dw
    source: VoteView
    unit: index
    transform: zscore
    data_vintage_available: true
    diversity_category: 'political'
    fixed_preprocessing_version: 'v1'
# (Add up to 15; keep diversity across macro/social/media/markets/surveys)
