version: "0.1"
composite: { crps: 0.5, brier: 0.5 }
diagnostics_only: [directional, temporal, magnitude]
calibration_targets:
  interval_coverages: [0.5, 0.9]
  reliability_diagrams: true
  pit_histograms: true
  tail_calibration: true
multivariate_postproc: { method: "ECC" }  # or "Schaake"
