composite:
  crps: 0.5
  brier: 0.5
diagnostics_only: [directional, temporal, magnitude]
calibration_targets:
  coverages: [0.5, 0.9]
  pit: true
  reliability: true
  tail_calibration: true
multivariate_postproc:
  method: ECC  # ECC or Schaake
  schaake_source: "data/processed/*.csv"
events:
  murphy_decomposition: true
