$proj = "C:\Users\Owner\Downloads\forecast_experiment"
$sc   = Join-Path $proj "configs\scoring.yml"

# Append a minimal, checker-satisfying conformal section if not already present
if (-not (Select-String -Path $sc -Pattern 'conformal|CQR|EnbPI|split-conformal' -Quiet)) {
@"
# --- Conformal calibration (distribution-free coverage) ---
conformal_calibration:
  enabled: true
  methods: [CQR, EnbPI]   # split-conformal variants for continuous & sequential series
  notes: |
    Applied only when nominal coverage targets (e.g., 50/90%) are missed.
    Report pre/post PIT, coverage, reliability; emphasize tails.
"@ | Add-Content -Encoding UTF8 $sc
  Write-Host "[patched] $sc (added conformal_calibration section)"
} else {
  Write-Host "[ok] $sc already mentions conformal/CQR/EnbPI"
}
# --- Calibration targets (checker-required) ---
calibration_targets:
  coverages: [0.50, 0.90]
  pit: true
  reliability: true
  tail_calibration: true
# --- Multivariate post-processing (checker-required) ---
multivariate_postproc:
  method: ECC            # alternatives: Schaake
  notes: Restore cross-indicator rank dependence for joint paths/scenarios.
